### ISSUE TITLE
Images package

### ISSUE THREAD

**Issue by dan-alarcon** [KIvanow/installedApps#1]
Hi, Congratulations on the development of this great plugin. Would you like to ask a question? Is it possible to receive the icons along with the package names? greetings

**Comment by KIvanow** [comment]
Hi Danmobilers, at the time I created this plugin I couldn't find a way to return the icons and I used to get them through a separate plugin I can not find at the moment.

**Comment by dan-alarcon** [comment]
Hello KIvanow, thank you for the brief return.
